#!/usr/bin/env bash 

if (( $# != 1 )); then # $# is the number of arguments passed to the script
  echo "Usage: $0 <name>"
fi

if [[ -n $1 ]]; then
  name=$1 
else 
  read -p 'Enter your name: ' name 
fi 

echo "Your name is: $name"

